import os

MARKET_SELLER_INN: str = os.getenv('MARKET_SELLER_INN')
MARKET_CAMPAIGN_ID: int = int(os.getenv('MARKET_CAMPAIGN_ID'))
MARKET_ACCESS_TOKEN: str = os.getenv('MARKET_ACCESS_TOKEN')

GOOGLE_SPREADSHEET_ID: str = os.getenv('GOOGLE_SPREADSHEET_ID')
GOOGLE_TOKEN_FILE_NAME: str = os.getenv('GOOGLE_TOKEN_FILE_NAME')
